<a href="https://colab.research.google.com/github/emmanuelmassawe/Car-Sales-Price-Prediction/blob/main/Car_Sales_Price_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

THIS IS CAR SALE PRICE PREDICTION
# New Section
THIS IS A WAY TO CREATE  ML PIPELINE

### import necessary library

In [34]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

In [4]:
### loading our dataset
df = pd.read_csv("car_purchasing.csv", encoding= "ISO-8859-1")

In [5]:
## print the first 5 rows
df.head(5)

,customer name,customer e-mail,country,gender,age,annual Salary,credit card debt,net worth,car purchase amount
0,Martina Avila,cubilia.Curae.Phasellus@quisaccumsanconvallis.edu,Bulgaria,0,41.851720,62812.09301,11609.380910,238961.2505,35321.45877
1,Harlan Barnes,eu.dolor@diam.co.uk,Belize,0,40.870623,66646.89292,9572.957136,530973.9078,45115.52566
2,Naomi Rodriquez,vulputate.mauris.sagittis@ametconsectetueradip...,Algeria,1,43.152897,53798.55112,11160.355060,638467.1773,42925.70921
3,Jade Cunningham,malesuada@dignissim.com,Cook Islands,1,58.271369,79370.03798,14426.164850,548599.0524,67422.36313
4,Cedric Leach,felis.ullamcorper.viverra@egetmollislectus.net,Brazil,1,57.313749,59729.15130,5358.712177,560304.0671,55915.46248

In [6]:
# print the shape of the data
df.shape

(500, 9)

In [7]:
df['country'].value_counts()

country
Mauritania                                      6
Israel                                          6
Bolivia                                         6
Kyrgyzstan                                      5
Samoa                                           5
                                               ..
Ukraine                                         1
New Zealand                                     1
Saint Helena, Ascension and Tristan da Cunha    1
Malaysia                                        1
marlal                                          1
Name: count, Length: 211, dtype: int64

In [8]:
# looking the unique value
df['country'].value_counts()

country
Mauritania                                      6
Israel                                          6
Bolivia                                         6
Kyrgyzstan                                      5
Samoa                                           5
                                               ..
Ukraine                                         1
New Zealand                                     1
Saint Helena, Ascension and Tristan da Cunha    1
Malaysia                                        1
marlal                                          1
Name: count, Length: 211, dtype: int64

In [9]:
## checking the dytpe
df.dtypes

customer name           object
customer e-mail         object
country                 object
gender                   int64
age                    float64
annual Salary          float64
credit card debt       float64
net worth              float64
car purchase amount    float64
dtype: object

In [10]:
# checking the infomation of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer name        500 non-null    object
 1   customer e-mail      500 non-null    object
 2   country              500 non-null    object
 3   gender               500 non-null    int64
 4   age                  500 non-null    float64
 5   annual Salary        500 non-null    float64
 6   credit card debt     500 non-null    float64
 7   net worth            500 non-null    float64
 8   car purchase amount  500 non-null    float64
dtypes: float64(5), int64(1), object(3)
memory usage: 35.3+ KB

In [11]:
## dropping unwanted columns
df = df.drop(['customer name','customer e-mail'], axis=1)

In [12]:
df.head()

,country,gender,age,annual Salary,credit card debt,net worth,car purchase amount
0,Bulgaria,0,41.851720,62812.09301,11609.380910,238961.2505,35321.45877
1,Belize,0,40.870623,66646.89292,9572.957136,530973.9078,45115.52566
2,Algeria,1,43.152897,53798.55112,11160.355060,638467.1773,42925.70921
3,Cook Islands,1,58.271369,79370.03798,14426.164850,548599.0524,67422.36313
4,Brazil,1,57.313749,59729.15130,5358.712177,560304.0671,55915.46248

In [13]:
# drop the target column and saving it in y
X = df.drop('car purchase amount', axis=1)
y = df['car purchase amount']

In [14]:
#separing categorical column and numerical columns

numerical_features = X.select_dtypes(include=['int64', 'float64']).columns
categorical_features = X.select_dtypes(include=['object']).columns

In [15]:
# print the numerical features and categorical features
print("Numerical Features:", numerical_features)
print("Categorical Features:", categorical_features)

Numerical Features: Index(['gender', 'age', 'annual Salary', 'credit card debt', 'net worth'], dtype='object')
Categorical Features: Index(['country'], dtype='object')

In [16]:
# filling the missing values and performing standardization
numerical_transformer = Pipeline(steps =[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler',StandardScaler())
])
# filling the missing values and changing categorical numerical values to numbers
categorical_transformer = Pipeline(steps = [
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

In [17]:
# combiing both categorical and numberical trough transformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ])

TRAIN OUR DATA

In [27]:
# we split our data
X_train,X_test,y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [28]:
# we train our model
model = Pipeline(steps= [
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())

])

In [29]:
# we fit in our data
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['gender', 'age', 'annual Salary', 'credit card debt', 'net worth'], dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['country'], dtype='object'))])),
                ('regressor', LinearRegression())])

In [32]:
# we perform predictions
y_pred = model.predict(X_test)

In [35]:
#we evaluate our model through test data if it has better prediction
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mse)

In [37]:
print("Mean Absolute Error (MAE):", mse)
print("R-squared (R2):", r2)
print("Root Mean Squared Error (RMSE):", rmse)

Mean Absolute Error (MAE): 2.791248946104145
R-squared (R2): 0.9999999741486777
Root Mean Squared Error (RMSE): 1.6707031292555075

In [38]:
# we check if there is any correlations
print(X.corr(numeric_only=True))

                    gender       age  annual Salary  credit card debt  \
gender            1.000000 -0.064481      -0.036499          0.024193
age              -0.064481  1.000000       0.000130          0.034721
annual Salary    -0.036499  0.000130       1.000000          0.049599
credit card debt  0.024193  0.034721       0.049599          1.000000
net worth        -0.008395  0.020356       0.014767         -0.049378

                  net worth
gender            -0.008395
age                0.020356
annual Salary      0.014767
credit card debt  -0.049378
net worth          1.000000

In [39]:
data = X.copy()
data["target"] = y

print(data.corr(numeric_only=True)["target"].sort_values(ascending=False))

target              1.000000
age                 0.632865
annual Salary       0.617862
net worth           0.488580
credit card debt    0.028882
gender             -0.066408
Name: target, dtype: float64

In [40]:
from sklearn.metrics import r2_score

y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

print("Train R²:", r2_score(y_train, y_train_pred))
print("Test R²:", r2_score(y_test, y_test_pred))

Train R²: 0.9999999904180696
Test R²: 0.9999999741486777