<a href="https://colab.research.google.com/github/emmanuelmassawe/Car-Sales-Price-Prediction/blob/main/Car_Sales_Price_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

THIS IS CAR SALE PRICE PREDICTION
# New Section
THIS IS A WAY TO CREATE  ML PIPELINE

### import necessary library

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_squared_error
import numpy as np

In [6]:
### loading our dataset
df = pd.read_csv("car_purchasing.csv", encoding= "latin1")

In [7]:
## print the first 5 rows
df.head(5)

     customer name  ... car purchase amount
0    Martina Avila  ...         35321.45877
1    Harlan Barnes  ...         45115.52566
2  Naomi Rodriquez  ...         42925.70921
3  Jade Cunningham  ...         67422.36313
4     Cedric Leach  ...         55915.46248

[5 rows x 9 columns]

In [8]:
# print the shape of the data
df.shape

(500, 9)

In [9]:
# looking the unique value
df['country'].value_counts()

country
Mauritania                                      6
Israel                                          6
Bolivia                                         6
Kyrgyzstan                                      5
Samoa                                           5
                                               ..
Ukraine                                         1
New Zealand                                     1
Saint Helena, Ascension and Tristan da Cunha    1
Malaysia                                        1
marlal                                          1
Name: count, Length: 211, dtype: int64