<a href="https://colab.research.google.com/github/emmanuelmassawe/Car-Sales-Price-Prediction/blob/main/Car_Sales_Price_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

THIS IS CAR SALE PRICE PREDICTION
# New Section
THIS IS A WAY TO CREATE  ML PIPELINE

### import necessary library

In [41]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_squared_error
import numpy as np

In [42]:
### loading our dataset
df = pd.read_csv("car_purchasing.csv", encoding= "ISO-8859-1")

In [43]:
## print the first 5 rows
df.head(5)

     customer name  ... car purchase amount
0    Martina Avila  ...         35321.45877
1    Harlan Barnes  ...         45115.52566
2  Naomi Rodriquez  ...         42925.70921
3  Jade Cunningham  ...         67422.36313
4     Cedric Leach  ...         55915.46248

[5 rows x 9 columns]

In [44]:
# print the shape of the data
df.shape

(500, 9)

In [45]:
df['country'].value_counts()

country
Mauritania                                      6
Israel                                          6
Bolivia                                         6
Kyrgyzstan                                      5
Samoa                                           5
                                               ..
Ukraine                                         1
New Zealand                                     1
Saint Helena, Ascension and Tristan da Cunha    1
Malaysia                                        1
marlal                                          1
Name: count, Length: 211, dtype: int64

In [46]:
# looking the unique value
df['country'].value_counts()

country
Mauritania                                      6
Israel                                          6
Bolivia                                         6
Kyrgyzstan                                      5
Samoa                                           5
                                               ..
Ukraine                                         1
New Zealand                                     1
Saint Helena, Ascension and Tristan da Cunha    1
Malaysia                                        1
marlal                                          1
Name: count, Length: 211, dtype: int64

In [47]:
## checking the dytpe
df.dtypes

customer name           object
customer e-mail         object
country                 object
gender                   int64
age                    float64
annual Salary          float64
credit card debt       float64
net worth              float64
car purchase amount    float64
dtype: object

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer name        500 non-null    object
 1   customer e-mail      500 non-null    object
 2   country              500 non-null    object
 3   gender               500 non-null    int64
 4   age                  500 non-null    float64
 5   annual Salary        500 non-null    float64
 6   credit card debt     500 non-null    float64
 7   net worth            500 non-null    float64
 8   car purchase amount  500 non-null    float64
dtypes: float64(5), int64(1), object(3)
memory usage: 35.3+ KB

In [49]:
## dropping unwanted columns
df = df.drop(['customer name','customer e-mail'], axis=1)

In [50]:
df.head()

        country  gender  ...    net worth  car purchase amount
0      Bulgaria       0  ...  238961.2505          35321.45877
1        Belize       0  ...  530973.9078          45115.52566
2       Algeria       1  ...  638467.1773          42925.70921
3  Cook Islands       1  ...  548599.0524          67422.36313
4        Brazil       1  ...  560304.0671          55915.46248

[5 rows x 7 columns]

In [51]:
X = df.drop('car purchase amount', axis=1)
y = df['car purchase amount']

In [52]:
numerical_features = X.select_dtypes(include=['int64', 'float64']).columns
categorical_features = X.select_dtypes(include=['object']).columns

In [53]:
print("Numerical Features:", numerical_features)
print("Categorical Features:", categorical_features)

Numerical Features: Index(['gender', 'age', 'annual Salary', 'credit card debt', 'net worth'], dtype='object')
Categorical Features: Index(['country'], dtype='object')

In [54]:
numerical_transformer = Pipeline(steps =[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler',StandardScaler())
])
categorical_transformer = Pipeline(steps = [
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

In [55]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ])

TRAIN OUR DATA

In [56]:
X_train , y_train, X_test, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [57]:
model = Pipeline(steps= [
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())

])

In [58]:
model.fit(X_train, y_train)

ValueError: could not convert string to float: 'Chile'